---
# Dev environment for local HIPPO development.
# Needs two containers, backend with HIPPO and dependencies installed, and database

# database container is built from images/postgres/Dockerfile:
# sudo docker build --no-cache  -t hippo-pg:latest .

# Backend from ./Dockerfile
# sudo docker build --no-cache . -t hippo-backend:latest

# Then bring the containers up with:
# sudo docker-compose up

# To clear the system run
# sudo docker compose down

# To also clear the datbase volume
# sudo docker compose down -v


services:

  # database:
  #   image: hippo-pg
  #   container_name: hippo_pg_db
  #   volumes:
  #   - postgres_data:/var/lib/postgresql/data
  #   - type: bind
  #     source: ./pg_setup/docker-entrypoint-initdb.d
  #     target: /docker-entrypoint-initdb.d
  #   env_file:
  #     - .env      
  #   ports:
  #   - "5432:5432"
  #   healthcheck:
  #     test: pg_isready -U postgres -d hippo
  #     interval: 10s
  #     timeout: 2s
  #     retries: 5
  #     start_period: 10s

  database:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     RDKIT_VERSION: ${RDKIT_VERSION:-Release_2025_09_5}
    #     BOOST_VERSION: ${BOOST_VERSION:-1.90.0}
    #     BOOST_VER_US: ${BOOST_VER_US:-1_90_0}
    #     PG_MAJOR: ${PG_MAJOR:-18}
    #     PG_BASE: ${PG_BASE:-postgres:18.3-bookworm}
    # image: xchem_designdb:latest
    # container_name: xchem_designdb
    image: xchem-hippo-pg
    container_name: hippo_pg_db    
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data      
    env_file:
      - .env       
    environment:
      POSTGRES_DB: ${DB_NAME:-designdb}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS:---auth-host=scram-sha-256 --auth-local=trust}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-scram-sha-256}
    shm_size: 8g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s
    networks:
      - app_network


  backend:
    image: hippo-backend
    container_name: hippo_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/home/code/HIPPO
    env_file:
      - .env
    ports:
    - "8888:8888"
    networks:
      - app_network    
    depends_on:
      database:
        condition: service_healthy


networks:
  app_network:
    name: xchem_designdb_network
    driver: bridge


volumes:
  postgres_data:
